import { supabase } from './supabase';

export interface BrainDocument {
    id: string;
    content: string;
    metadata: Record<string, any>;
    similarity?: number;
}

export interface AskBrainResponse {
    answer: string;
    documents: BrainDocument[];
}

/**
 * Sends content to be embedded and stored in the Corporate Brain.
 * @param content The text content to store.
 * @param metadata Additional metadata (source, author, type, etc.)
 */
export async function addToBrain(content: string, metadata: Record<string, any> = {}) {
    const { data, error } = await supabase.functions.invoke('embed-content', {
        body: { content, metadata },
    });

    if (error) {
        console.error('Error adding to brain:', error);
        throw error;
    }

    return data;
}

/**
 * Asks a question to the Corporate Brain.
 * @param query The user's question.
 * @returns The answer generated by AI and the source documents used.
 */
export async function askBrain(query: string): Promise<AskBrainResponse> {
    const { data, error } = await supabase.functions.invoke('chat-brain', {
        body: { query },
    });

    if (error) {
        console.error('Error asking brain:', error);
        throw error;
    }

    return data;
}
