
-- Create ai_feedback table
create table if not exists ai_feedback (
  id bigint generated by default as identity primary key,
  user_email text not null,
  message text not null,
  is_read boolean default false,
  created_at timestamptz default now(),
  read_at timestamptz
);

-- Add index for performance on user_email
create index if not exists idx_ai_feedback_user_email on ai_feedback(user_email);
create index if not exists idx_ai_feedback_is_read on ai_feedback(is_read);

-- Enable RLS
alter table ai_feedback enable row level security;

-- Policies
-- Users can see their own feedback
create policy "Users can view their own feedback" on ai_feedback
  for select using (auth.email() = user_email);

-- Users can update their own feedback (to mark as read)
create policy "Users can update their own feedback" on ai_feedback
  for update using (auth.email() = user_email);

-- Service/Admin can insert (assuming service role or admin usage)
create policy "Enable insert for authenticated users" on ai_feedback
    for insert with check (true);
